#! /bin/sh
# File: rmtrash
# Func:  remove trash files such as "core" and "*.tmp"
# Usage: rmtrash
trash=$$.$$ 
echo "** Remove trash started. …"
echo
find $HOME -name "*.tmp" -print	>$trash
find $HOME -name core -print	>>$trash
for i in `cat $trash` 
do
	if [ ! -d $i ]
	then
#		rm $i
		echo $i
	fi
done
rm $trash
echo "** Remove trash finished."
